gtr_expected_proxy_ports:
- 1080
- 7890
tailscale_p2p_heal_enabled: true
tailscale_p2p_peer_name: vmaliyun
tailscale_p2p_peer_ip: 100.100.99.70
github_download_proxy: http://127.0.0.1:7890
k3s_containerd_http_proxy: "http://127.0.0.1:7890"
k3s_containerd_https_proxy: "http://127.0.0.1:7890"
k3s_registry_mirrors:
  docker.io:
    - "https://quqdq6jy.mirror.aliyuncs.com"
k3s_node_labels:
  gtr.io/region: cn
  gtr.io/visibility: internal
ansible_ssh_common_args: '-o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o ConnectTimeout=30'
gtr_ai_user: lynskylate
slock_ai_label: tiequn-misc
slock_ai_server_url: https://api.slock.ai
