gtr_expected_proxy_ports:
- 1080
- 7890
github_download_proxy: http://127.0.0.1:7890
k3s_containerd_http_proxy: "http://127.0.0.1:7890"
k3s_containerd_https_proxy: "http://127.0.0.1:7890"
k3s_registry_mirrors:
  docker.io:
    - "https://quqdq6jy.mirror.aliyuncs.com"
k3s_node_labels:
  gtr.io/region: cn
  gtr.io/visibility: internal
ansible_ssh_common_args: '-o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o ConnectTimeout=30'
gtr_ai_user: lynskylate
slock_ai_label: tiequn-misc
slock_ai_server_url: https://api.slock.ai
