---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mihomo-exit-auth
  namespace: networking
spec:
  encryptedData:
    TS_AUTHKEY: AgAgcMgDPEL0w3TWpfsEtu6SvGpVRQBSdJDgwN/rpmLDOjqT4ghOQeMdXKVadEwEVqOY9Drs1w91/mmIUYQ0EDgjpOoL8rYTEvPrF0mk88tfpluxM12N/bUuZxkHZDvMNKLW1jOELuUE3idYkrQiq+UFLyX/cUnM8G0/SRfPlNK6bFQs5WiGqV0FK/PhETpfq+s2/BBsAOz1Kr0gcgalI1JCToamY4g16fNo3YInAdgzOYL3PdgxI93e9bAiXCOHpyLyQDCCeD9XQVPwAmYXP7uIwOSdsU1n81rc3Hnj3LoRc9ca44l/yERfgo5wtyOBU8F758Z3cUdMp39PGP6qg+QLG4+m5tmJqrvmD0ziUIUVM7mXw1WKHzASwlvcIbVsgyHmkPBcvrOrOVJV/AkXB1dkAo/iBc14c5/62EcwbymD9xDIhS+0XA/FBvCN2SDJlbOhadNtf0Qe3FoWHWMSYXQY2HszpSgJ2JsmWAP3NXQutD6Xi+1E9O44DutlNHbZOIw7lc8zxrq+Ojdaw2sDMxRozrDwjBosQoVR4+PY8uhSwWMXBi7iXdcvJO1zhLd3ujat1okUiYqJFrHYNGssrCMZpSuMqeKxDsivhUEiRDMlFo6l8wS8WbiwbuAe9F6+dBd3lDrI8NaSW5nMzRQu2GWpdW5Q3vbkAa/EAchdqz8DjYfuMDBZBuYNtiHaDxoaUNrixC8QxBqIuu/SL/e+O8MNsOjNS/YD284En9+1s7OKonYdEfG5Ho+RvsMTuRSGqfEdmpfokRC5VWc994dqFOg=
  template:
    metadata:
      creationTimestamp: null
      name: mihomo-exit-auth
      namespace: networking
