---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mihomo-exit-api
  namespace: networking
spec:
  encryptedData:
    MIHOMO_API_SECRET: AgAu0oZPN2Lx3r8BgsIhCwncQMhqMiRn8Ar8C/R0OpXmjsC2M0dHNX1PmaDBW8JUWQPjXQSBCX/sleheJnB0NxE3iQvl800AYzHyoB4+0MQ7l2DZeGWkvCPEVjBPScTz8WAdNY6gFXFKHZaFaBHG4T+1Ubb8Gu7aQ4qNU9ro1lhC7sDfkRvO2caj2GFqDlF7yku2ohCk/GAuCwtiL/u6Tqy5qpsDcVAmmpe97qQUoRaH5skCd2NDoiR2OB5aoETCR4xEWMPGowHcbUr/7s4TlNMBP+efNVJbyGPaaERHew9WnWsDSgpATQLtC8ffPfRkQAUEE6DX+5zHzs/LtEo7/5ctRUKx6ldtvLx7zNvUcA5SJUS/Lgx4tmh8U1jvTU803H6E6n5LWdNWJWFTeK8leGR3YJByFjOVgDXoIgZz/h4mSQpWm4+Yuk09tGZyVkjZS2U3yG7CFs2PGCaEmZHaNebx4vDXemhDL/8XoQRqCOhDjCWxbTVX/r+8/KDlheNbZbtNc5/CgezXMxcb9ma59D5y04sfzPnDB50LIdrqF3ecSLLDlMzMTQNFlhWst23t6Ff3RrYtBGefNRjbO0jJ7bYDHzHB4PricPa3Bh81wckCr3CYPSj0BJWhCajm0hZ0tcH53PJL4ReTJNlqKiJeOdIDimzmCSY+9C6/hR2pEMOARnZLGXluADRgZphnn0uCW1bIhUdjqDJh0/hB24Vro0+Jk+2JewxZFS3Spi97D0Pk3Q==
  template:
    metadata:
      creationTimestamp: null
      name: mihomo-exit-api
      namespace: networking
