{
 "title": "mihomo",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "UP Proxy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mihomo_proxy_up{proxy_group=\"Auto\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(mihomo_proxy_up{}) by (proxy_group, type) == 1)",
     "legendFormat": "Availaible Node"
    },
    {
     "expr": "count(sum(mihomo_proxy_up{}) by (proxy_group, type) != 1)",
     "legendFormat": "UnAvailaible Node"
    }
   ]
  },
  {
   "title": "非大陸站時延",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "container_name:\"network-monitor\"\r\n_time:$__range\r\nexpected_route:proxy\r\n| stats by(site) max(response_time) as avg_response_time\r\n| sort by (avg_response_time desc)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "container_name:\"network-monitor\" expected_route:direct _time:$__range\r\n| stats by(_time:1m, site) max(response_time)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "直連時延",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "container_name:\"network-monitor\"\r\n_time:$__range\r\nexpected_route:direct\r\n| stats by(site) max(response_time) as avg_response_time\r\n| sort by (avg_response_time desc)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "container_name:\"network-monitor\" expected_route:proxy _time:$__range\r\n| stats by(_time:1m, site) max(response_time)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(mihomo_traffic_download_total_bytes[5m])) by(server)",
     "legendFormat": "DownloadSpeed {{server}}"
    },
    {
     "expr": "avg(rate(mihomo_traffic_upload_total_bytes[5m])) by(server)",
     "legendFormat": "UploadSpeed {{server}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "count(mihomo_proxy_selected) by(proxy_group, proxy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "table",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "_time:$__range AND _stream.log_type:=\"connection\" | stats by(_stream.log_level, _stream.dest_host, _stream.proxy, _stream.rule_pattern) count()"
    }
   ]
  }
 ]
}