apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-monitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lynskylate/nas-deployment-public.git
    path: platform/resources/network-monitor
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
