apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriatraces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-traces-single
    targetRevision: 0.x
    helm:
      values: |
        server:
          podSecurityContext:
            enabled: true
            fsGroup: 993
            runAsGroup: 993
            runAsNonRoot: true
            runAsUser: 989
          persistentVolume:
            enabled: true
            existingClaim: victoriatraces-data
          extraArgs:
            envflag.enable: "true"
            envflag.prefix: VM_
            loggerFormat: json
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
          nodeSelector:
            kubernetes.io/hostname: gtr
          service:
            annotations:
              tailscale.com/expose: "true"
              tailscale.com/proxy-class: gtr-only
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
