---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mihomo-api
  namespace: monitoring
spec:
  encryptedData:
    MIHOMO_SECRET: AgBbbVyz1JWmwDHivP+aK794QKvA0Z3GFNUhRse9RnfVDyexbzWfJ7gejSAbmiGeVUCHz7xM0tgWGPv/ew+umbEiS1N9GsqMGpa7yTSKDk6VzrXuPNrwcfAgt7jIjHRzw5BEc5gZ6eQa9XmgOTcgWWl8yln3hLNiVd7PYm3NwPq/bpIX4wBjJXTMaYBO996ZYmH76X2LGrHrKm6NH8c1RT+xA9coCtD1xqhUKlhBwHi6/a4MeKoJalBYc5oLV9dZGgmAxy7+JtdTrlycUpXX50YNEUNtNFot5MhKl+9soDUFaub5mzBK/29XBF2MzMeUHzcsH4xG5S5FVjQA8xpjXYzzoQ2goxqyRkPj2dsbLLrGu/KoVeyAXAOY6A7Jkgn1kH3GlOS6whXVOHHnTWWTb4qzR63wso8yUk8a6on0hAb87nG++ijGT2QzCLeHzHzeNJccddtKyqiJpsn5GmZMcxR8qiNOnj0gsstMAbKsU4prC4aKF6fd+WOMORyDDo7hX1YPhcLRaqqzOKV47+OCu3FbRxPasn0RYCDXq2T39MflFVWDTAUIQi7iORLmZcCtlLB8MDQZ/hC1JJuqLLsBs31xzUNYY8Alz1evhQvZI2gWp8yQbNXmd4Sq6c0uadRFMBsejgHbWyzaphqaRlku/99ZtO0YstL43OjX5zMJHR0CePJFJRNAio3fr4972tSF3sVYmI4cBOw3bZHvJOEgbKTHZU6HlRF8dl8YRqcTACs6wQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mihomo-api
      namespace: monitoring
