---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mihomo-api
  namespace: monitoring
spec:
  encryptedData:
    MIHOMO_SECRET: AgCxgAQrjPNahEUJtTsBO/ty61UUBOLa1Fld9d+jOscx2Db1/AVM/9H11NAKu2qfjVET+agfuwXMxUn/ifAgv6GN2jqHZGoHBWKc/IgHpt3tAgJtPGH1Qx6hwOydK7rZSviBIxG0ayp7pnZJ4D63Nvh0je+n2mZAv+b/zg3Rc43KpPGQamM6SwteIY9WzgalA0YuqYNEMroXi9l/rJ8sQW4eJJU1EvOl17sDkfqgJ/vdobJC8n6EEpQM7uuLmQOxMj7jVt6ezdjvCTzzAL4hEw7qNH/cFnnleAQ2Aa8R27WbMMWHoZoHUJtdDMYBwDYlD0RdCHrYVpKxgA38cl57gWoLmfgxjMLcj0R55lrDlBJPnrCmILJJ4LQbJfgMkcvIyBA4h2YUJxdxuLpIbotcXVTAvVVR3S01ihp/blIjHLQbkIkz8j3rjAa222D+lYR1VVV8/A3nr1e7ta6RrzphhHYwUEawTJo414nIvV8ZY00Fmw9DTuVxHYacfBrM/8Vra2DhH8QWirsWrb/wpvbroEOWG51R3lZxOt0F/zNU3XL713V9kzSVzA3sskZ10Y49IsB4aQMuRCJzkDutRMxM5L7SiOpc/EzVmkMBJmnGThafv2hSfr0iRcZZBas95f4o5M4UFQgUptzF/uCH8Yxmf6DkD80z5PJ13oX3CwQncx9aZi4iJRgMSLs6TyZfCLBkzvd2ScSw/B4hT+CN+L5S7DNUoXhC5GX8lIKFqUrQhw3klg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mihomo-api
      namespace: monitoring
