---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: mihomo-api
  namespace: monitoring
spec:
  encryptedData:
    MIHOMO_SECRET: AgAoiImBL2QvgToCMzwhSOHjwbIbfOCkz/MadzkAuzU1WeBh91Gt5Li820UnaQKHHbDhkS6EvwzIk8tWY36pminjE60Z874/R00wsDfInbfxTIt1yQlCZfNh2B2MXLkxZxT/qgjalqgyxL4MS/yNjOcprCBQQhgoR7bLqP9W6KdsysGb86BB9npIwD3cOGykmAYZ3zJ0YMdTuYCjKImPS/sBINu1LsQIqE063dtp6lhQT/0Hywi8PdlShVV7+sTTlG28Rs9nq14wPpKbH5OvP+P7VRuAgaiLYZyB4SJB6rQ/a0V71fWY5UV+wJ4J9g41pQyIJYL7NTTats4pn+/ExjK/JA830hupX4XxJSrqsCe9+4VWPbvS4St5jopj8iBcv0qTiUTLOMAWm0LOn0QmZlxLV0bpV4vL8Up0zUrSz83EvS3C9/45rf6gSMkbVWzBGykjKzAyDA72rBqqjAsMYUlWQ2EDgKJcQ6OV+Gbpc7sIwACQyLjECz+tlpplWZwmxdxB03/u37KrMfJTAP8UaIoD3jFj9zmx/Zum2Cyk/0XB0AGWN7BgwXdyGCM9fH60rAHyQF51nqqpk+671ZGgwx6eiuXC26BmwqdbFnhgvZlhU7lA6Wenf1X9XNj6I9pBqawMdgJv6DXKh/B8D7MvinYWfS4aVyHW0FZsAlG7s6sWZKocuKNdgh9ezwNl5h/X2wqvCNUv10zJ9O08P31BTbTB8TgTF/SpehnPpLns4JoqYg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: mihomo-api
      namespace: monitoring
