#!/usr/bin/env bash
# gen-manifest.sh — 从 gtr-services group_vars 生成资源 manifest
# 用法: ./scripts/gen-manifest.sh [output-path]
# 默认输出到仓库根目录的 .resource-manifest.yml

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="${1:-$REPO_ROOT/.resource-manifest.yml}"

GROUP_VARS="$REPO_ROOT/edge/ansible/group_vars/all/public.yml"

if [[ ! -f "$GROUP_VARS" ]]; then
  echo "ERROR: group_vars/all/public.yml not found at $GROUP_VARS" >&2
  exit 1
fi

# 提取 subuid 分配 (resource_subuid_allocations)
extract_subuid() {
  python3 -c "
import yaml, sys
with open('$GROUP_VARS') as f:
    data = yaml.safe_load(f)
allocs = data.get('resource_subuid_allocations', [])
for a in allocs:
    print(f'  - user: {a[\"user\"]}')
    print(f'    start: {a[\"start\"]}')
    print(f'    size: {a[\"size\"]}')
"
}

# 提取端口分配 (resource_port_allocations)
extract_ports() {
  python3 -c "
import yaml, sys
with open('$GROUP_VARS') as f:
    data = yaml.safe_load(f)
allocs = data.get('resource_port_allocations', [])
for a in allocs:
    print(f'  - port: {a[\"port\"]}')
    print(f'    protocol: {a.get(\"protocol\", \"tcp\")}')
    print(f'    service: {a[\"service\"]}')
"
}

# 提取服务用户 (resource_service_users)
extract_users() {
  python3 -c "
import yaml, sys
with open('$GROUP_VARS') as f:
    data = yaml.safe_load(f)
users = data.get('resource_service_users', [])
if not users:
    print('  []')
else:
    for u in users:
        print(f'  - user: {u[\"user\"]}')
        if 'uid' in u:
            print(f'    uid: {u[\"uid\"]}')
"
}

# 生成 manifest
cat > "$OUTPUT" <<HEADER
# Auto-generated by scripts/gen-manifest.sh
# DO NOT EDIT MANUALLY — regenerate from group_vars
schema_version: 1
layer: infrastructure
generated_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

subuid:
HEADER

extract_subuid >> "$OUTPUT"

cat >> "$OUTPUT" <<MID

ports:
MID

extract_ports >> "$OUTPUT"

cat >> "$OUTPUT" <<MID2

users:
MID2

extract_users >> "$OUTPUT"

cat >> "$OUTPUT" <<FOOTER

nftables_chains:
  - ts-forward
  - ts-input
  - ts-postrouting
FOOTER

echo "Generated: $OUTPUT"
echo "  subuid: $(grep -c '  - user:' "$OUTPUT" 2>/dev/null || echo 0) entries"
echo "  ports:  $(grep -c '  - port:' "$OUTPUT" 2>/dev/null || echo 0) entries"
